#!/bin/bash

# Author Marcelo Miranda Carneiro -- mcarneiro@fbiz.com.br | mcarneiro@gmail.com

set -o nounset
set -o errexit
set -o pipefail

B1="\033[1m";
B2="\033[0m";
ARGS=( "${@:-}" );
UPLOAD_URL='http://css.spritegen.com/api.php?upload';
CREATE_URL='http://css.spritegen.com/api.php?create';
FILE_LIST='';
INPUT_PATH=${1:-./};
OUTPUT='';
QUIET='';
CREATED_DATA='';
SESSION_ID='';
TO_SEND=();
TOTAL=0;
UPLOADED=0;

help() {
	if [ "${ARGS[0]}" = "?" ]; then
			echo -e "
CSS Sprite v0.1

${B1}AUTHOR${B2}
  Marcelo Miranda Carneiro - mcarneiro@gmail.com

${B1}INFO${B2} (release Thu Jul 26 15:10:13 BRT 2012)
  Generates a sprite via http://css.spritegen.com/ website and print out the CSS.

${B1}USAGE${B2}
  css-sprite [FOLDER_PATH] [-s, -o=OUTPUT_PATH]

  ${B1}-s${B2}  silent mode. Only outputs the generated CSS on the stdout;
  ${B1}-o${B2}  output png file. If nothing is passed, will use the folder
      name and output at the same directory;

  After the first run, a ${B1}sprite.config${B2} file will be created with the file
  list. It is possible to create a simple replace rule so the generated
  CSS classes doesn't need to follow the filenames. The rule for this
  file is something like:

  file-name.png=.new-css-rule:hover, .in-one-line
  file-name2.png
  file-name3.png=a.css-rule:hover

  When sprite.config exists, the script will ONLY use the listed files
  instead of listing through the folder.

  Known Bug:
  1. As the replace happens line-by-line on sprite.config, be carefull with
     the file names. On the example above, the order should
     be changed to avoid wrong replacement:

     file-name=.test
     file-name2=.second-test
     file-name3=a:hover

     the output css will be wrongly replaced:

     .test { background-position ...
     .test2 { background-position ...
     .test3 { background-position ...
     
     Changing the order will fix the behaviour:

     file-name3=a:hover
     file-name2=.second-test
     file-name=.test

${B1}EXAMPLES${B2}
  css-sprite ~/sprites/structure
  css-sprite ~/sprites/structure -s
  css-sprite ~/sprites/structure -o=teste.png
  css-sprite ~/sprites/structure -s | pbcopy (to copy to clipboard)
";
			exit 1;
	fi
}
# FORMAT AND MESSAGES
getColorId() {
	# color [isbg=""]
	local BG=''
	local COLOR=''
	
	case "${1:-}" in
		'black'|0) COLOR='0' ;;
		'red'|1) COLOR='1' ;;
		'green'|2) COLOR='2' ;;
		'yellow'|3) COLOR='3' ;;
		'blue'|4) COLOR='4' ;;
		'purple'|5) COLOR='5' ;;
		'cyan'|6) COLOR='6' ;;
		'gray'|7) COLOR='7' ;;
	esac
	if [ "$COLOR" ]; then
		BG='3'
	fi
	if [ "${2:-}" -a "$COLOR" ]; then
		BG='4'
	fi
	echo "${BG}${COLOR}"
}
getStyleId() {
	# [style="none"]
	local STYLE=''
	
	case "${1:-}" in
		'bold'|1) STYLE='1' ;;
		'underscore'|4) STYLE='4' ;;
		'blink'|5) STYLE='5' ;;
		'reverse'|7) STYLE='7' ;;
		'concealed'|8) STYLE='8' ;;
		'none'|0|*) STYLE='' ;;
	esac
	echo "$STYLE"
}
getFormatCode() {
	# [color="white" style="none" bgcolor=""]
	local ATTR=(
		"`getColorId \"${3:-}\" 1`"\
		"`getColorId \"${1:-}\"`"\
		"`getStyleId \"${2:-}\"`"
	)
	local OPENTAG=''
	local CLOSETAG='\033[0m'
	local CURR=''
	local i
	# echo \${ATTR[@]}: ${ATTR[@]}
	for(( i=0; i<${#ATTR[@]}; i++ )); do
		CURR=${ATTR[i]}
		if [ -z "$OPENTAG" ]; then
			OPENTAG='\033['
		fi
		if [ -n "$CURR" ]; then
			OPENTAG="${OPENTAG};${CURR}"
		fi
	done
	if [ -n "$OPENTAG" ]; then
		OPENTAG="${OPENTAG}m"
	fi
	echo "${OPENTAG}{txt}$CLOSETAG"
}
format() {
	# text [color="white" style="none" bgcolor=""]
	TXT=`echo ${1:-}`
	echo -e `getFormatCode ${2:-} ${3:-} ${4:-} | awk -F '{txt}' -v t="$TXT" '{print$1't'$2}'`
}

# METHOD UTILITIES
getArg() {
	## get args in the format "-argname=value"
	# arg_name
	# bool
	# custom_args
	local CURRARG=""
	local HASDASH=""
	local GETNEXTVALUE=""
	local a=""
	local CUSTOM_ARGS=( "${3:-}" )

	if [ -z "$CUSTOM_ARGS" ]; then
		CUSTOM_ARGS=( ${ARGS[@]} )
	fi

	HASDASH=`echo $1 | awk -F "^-+" '{print$2}'`
	if [[ -n "$HASDASH" ]]; then
		for(( i=0; i<${#CUSTOM_ARGS[@]}; i++ )); do
			a=${CUSTOM_ARGS[$i]}
			if [ "$a" == "$1" ]; then
				GETNEXTVALUE="1"
				if [ "${2:-}" == '1' ]; then
					CURRARG='1';
					break;
				fi
				continue;
			fi
			if [[ "$GETNEXTVALUE" == "1" ]]; then
				CURRARG=$a
				break;
			fi
		done
	else
		for(( i=0; i<${#CUSTOM_ARGS[@]}; i++ )); do
			a=${CUSTOM_ARGS[$i]}
			CURRARG=`echo $a | awk -F "$1=" '{print$2}'`
			if [ "$CURRARG" != "" ]; then
				break;
			fi
		done
	fi
	echo $CURRARG
}

# log stuff
QUIET=''
WARN=''
log() {
	# text [style]
	if [ -z "$QUIET" ]; then
		local COLOR
		local STYLE
		local MSG=' [LOG]'
		local TXT=${1:-}
		
		case "${2:-}" in
			'success')
				MSG=' [SUCCESS]'
				COLOR='green'
				STYLE='bold'
			;;
			'title')
				MSG=''
				COLOR='white'
				STYLE='bold'
				TXT=`echo $TXT | tr 'a-z' 'A-Z'`
			;;
			'warn')
				MSG=' [WARNING]'
				COLOR='yellow'
			;;
		esac
		
		if [[ -n "$TXT" ]]; then
			MSG="$MSG $TXT"
		else
			MSG=''
		fi
		format "$MSG" "$COLOR" "$STYLE"
	fi
}
warn() {
	# text
	WARN="1"
	log "${1:-}" "warn"
}
success() {
	# text
	log "${1:-}" "success"
}
title() {
	# text
	log "${1:-}" "title"
}
finish() {
	log
	if [ -n "$WARN" ]; then
		warn "FINISHED with some warnings."
	else
		success "FINISHED!"
	fi
	log
}

# arguments
verifyArgumens() {
	OUTPUT="`getArg o`";
	QUIET="`getArg -s 1`";
	
	if [ -n "`echo $INPUT_PATH | awk -F '/' '{print$(NF)}'`" ]; then
		INPUT_PATH="$INPUT_PATH/";
	fi;

	if [ -d $INPUT_PATH ]; then
		CONFIG_FILE="${INPUT_PATH}sprite.config";
		if [ ! -f $CONFIG_FILE ]; then
			ls -l $INPUT_PATH | grep -E "[0-9]{2,2}:[0-9]{2,2}" | grep -E "(jpg|jpeg|gif|png)" | awk '{print$(NF)}' | sort -r > $CONFIG_FILE;
		fi
	fi

	getConfig $CONFIG_FILE;
	
	if [ -z "$OUTPUT" ]; then
		OUTPUT="../`basename "$INPUT_PATH"`.png";
	fi
}
getConfig() {
	local CUSTOM_ARGS
	if [ -f "${1:-}" ]; then
		FILE_LIST=`cat ${1:-}`;
	fi
}
getSessionID() {
	SESSION_ID="`curl -si $UPLOAD_URL | grep "PHPSESSID=" | awk -F 'PHPSESSID=' '{print$2}' | awk -F '; path=' '{print$1}'`"
}

upload() {
	if [ -f "${1:-}" ]; then
		log "Uploading image $1";
		local FILENAME=""; # commenting to make it work on git-bash "`file $1 | awk -F ':' '{print$1}' | awk -F '/' '{print$(NF)}'`";
		local RETURN_MSG="`curl -s -F img=@$1 -F Filename=$FILENAME $UPLOAD_URL -b PHPSESSID=$SESSION_ID`";
		if [ -z "`echo $RETURN_MSG | grep 'Uploaded successfully'`" ]; then
			warn "failed to upload $FILENAME. Details below:";
			warn "  $RETURN_MSG";
			exit 2;
		else
			echo '. ' >> css-sprite.temp;
			echo "$1 : $RETURN_MSG" > css-sprite.log;
		fi
	fi
}
uploadFiles() {
	IFS=$'\n';
	toUpload=();
	TOTAL=( $FILE_LIST );
	TOTAL=${#TOTAL[@]};
	echo '' > css-sprite.temp
	for a in $FILE_LIST; do
		# sleep 0.1s;
		upload "${INPUT_PATH}`echo $a | awk -F '=' '{print$1}'`" &
	done;
	IFS=' ';
}
create() {
	echo `curl -s $CREATE_URL -F output_type=png -F jpeg_quality=75 -F padding=2 -b PHPSESSID=$SESSION_ID`;
}
getCSS() {
	local CSS=`echo $1 | awk -F "Generated by" '{print Generated by$2}' | awk -F '"' '{print$1}'`;
	IFS=$'\n';
	for a in $FILE_LIST; do
		local FROM="\\.`echo $a | awk -F '=' '{print$1}' | awk -F '.' '{print$1}'`";
		FROM=${FROM//'_'/'-'};
		local TO=`echo $a | awk -F '=' '{print$2}'`;
		if [ ! -z "$TO" ]; then
			CSS=`echo $CSS | sed "s/${FROM}/${TO}/g"`;
		fi
	done;
	IFS=' ';
	echo ${CSS//'\n'/'^'} | tr '^' '\n'; #monster migué
}
getSprite() {
	echo "DATA = ${1:-}" > css-sprite.log;
	SPRITE_URL=`echo ${1:-} | awk -F '"url":"' '{print$2}' | awk -F '"' '{print$1}'`;
	SPRITE_URL=${SPRITE_URL//"\\"/""};
	curl -s -l $SPRITE_URL > "${INPUT_PATH}${OUTPUT}";
}

# run
help
if [ -f 'css-sprite.temp' ]; then
	rm css-sprite.temp;
fi;

verifyArgumens
getSessionID

title "Step 1 - Uploading files."
uploadFiles

UPLOADED=0;
while [ "$UPLOADED" -lt "$TOTAL" ]; do
	DUMMY=( `cat css-sprite.temp` );
	UPLOADED=${#DUMMY[@]};
	# wait me
done;
rm css-sprite.temp;
# sleep 0.5s;
success "OK";
CREATED_DATA="`create`"

title "Step 2 - Loading generated image."
getSprite "$CREATED_DATA";
success "OK";

title "Step 3 - Loading generated CSS."
getCSS "$CREATED_DATA";
success "OK";

# echo $OUTPUT
success "Generated file at ${INPUT_PATH}${OUTPUT}";