#!/bin/bash

# quick way to get svn revision. useful for using in another functions
# usage svn-rev [FOLDER]

if [ "$1" = "?" ]
	then
		B1="\033[1m";
		B2="\033[0m";
		echo -e "";
		echo -e "${B1}AUTHOR${B2}";
		echo -e "  Marcelo Miranda Carneiro - mcarneiro@gmail.com";
		echo -e "";
		echo -e "${B1}INFO${B2} (release 2011-01-11)";
		echo -e "  quick way to get svn revision. useful for using with another functions";
		echo -e "";
		echo -e "${B1}USAGE${B2}";
		echo -e "  svn-rev [FOLDER]";
		echo -e "";
		exit 1;
fi


svn info $1 | grep "Revision:" | awk '{print$2}'
