#!/bin/bash

# Apply defaults svn:ignore from http://bit.ly/mcarneiro-svni
# svn-psi [FOLDER]

if [ "$1" = "?" ]
	then
		B1="\033[1m";
		B2="\033[0m";
		echo -e "";
		echo -e "${B1}AUTHOR${B2}";
		echo -e "  Marcelo Miranda Carneiro - mcarneiro@gmail.com";
		echo -e "";
		echo -e "${B1}INFO${B2} (release 2011-01-11)";
		echo -e "  Apply defaults svn:ignore from http://bit.ly/mcarneiro-svni";
		echo -e "";
		echo -e "${B1}USAGE${B2}";
		echo -e "  svn-psi [FOLDER]";
		echo -e "";
		exit 1;
fi

PARAMS="$1"
if [ -z "$PARAMS" ]
	then
		PARAMS="."
fi

svn pset svn:ignore "`curl -sL http://bit.ly/mcarneiro-svni`" $PARAMS
